from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1053, 845)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(370, 10, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(48)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 90, 1011, 711))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 530, 371, 81))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.listView_2 = QtWidgets.QListView(self.groupBox_2)
        self.listView_2.setGeometry(QtCore.QRect(10, 40, 256, 21))
        self.listView_2.setObjectName("listView_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 40, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.video_2 = QtWidgets.QWidget(self.tab_2)
        self.video_2.setGeometry(QtCore.QRect(20, 10, 451, 491))
        self.video_2.setStyleSheet("")
        self.video_2.setObjectName("video_2")
        self.label_3 = QtWidgets.QLabel(self.video_2)
        self.label_3.setGeometry(QtCore.QRect(400, 120, 111, 16))
        self.label_3.setObjectName("label_3")
        self.widget_2 = QVideoWidget(self.video_2)
        self.widget_2.setGeometry(QtCore.QRect(20, 10, 921, 351))
        self.widget_2.setObjectName("widget_2")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.widget_2)
        self.tabWidget_3.setGeometry(QtCore.QRect(-40, -30, 971, 621))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.listView_5 = QtWidgets.QListView(self.tab_2)
        self.listView_5.setGeometry(QtCore.QRect(540, 10, 391, 391))
        self.listView_5.setObjectName("listView_5")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 530, 371, 81))
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.listView_3 = QtWidgets.QListView(self.groupBox_6)
        self.listView_3.setGeometry(QtCore.QRect(10, 40, 256, 21))
        self.listView_3.setObjectName("listView_3")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_14.setGeometry(QtCore.QRect(290, 40, 75, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.listView_7 = QtWidgets.QListView(self.tab_5)
        self.listView_7.setGeometry(QtCore.QRect(20, 20, 951, 481))
        self.listView_7.setObjectName("listView_7")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(420, 530, 371, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.listView_4 = QtWidgets.QListView(self.groupBox_3)
        self.listView_4.setGeometry(QtCore.QRect(10, 40, 256, 21))
        self.listView_4.setObjectName("listView_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(290, 40, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.video = QVideoWidget(self.tab)
        self.video.setGeometry(QtCore.QRect(20, 10, 951, 491))
        self.video.setStyleSheet("")
        self.video.setObjectName("video")
        self.label_2 = QtWidgets.QLabel(self.video)
        self.label_2.setGeometry(QtCore.QRect(400, 120, 111, 16))
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(self.video)
        self.horizontalSlider.setGeometry(QtCore.QRect(150, 450, 791, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.pushButton_2 = QtWidgets.QPushButton(self.video)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 430, 41, 41))
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../OneDrive/바탕 화면/갈매기/asdf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.video)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 430, 41, 41))
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../OneDrive/바탕 화면/갈매기/pause.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.widget = QVideoWidget(self.video)
        self.widget.setGeometry(QtCore.QRect(20, 10, 921, 391))
        self.widget.setObjectName("widget")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.widget)
        self.tabWidget_2.setGeometry(QtCore.QRect(-40, -50, 971, 621))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(450, 160, 71, 16))
        self.label.setObjectName("label")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(30, 530, 371, 81))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setGeometry(QtCore.QRect(10, 40, 256, 21))
        self.listView.setObjectName("listView")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(290, 40, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.listView_8 = QtWidgets.QListView(self.tab_6)
        self.listView_8.setGeometry(QtCore.QRect(20, 20, 951, 481))
        self.listView_8.setObjectName("listView_8")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 510, 371, 81))
        self.groupBox_7.setFlat(False)
        self.groupBox_7.setCheckable(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.listView_9 = QtWidgets.QListView(self.groupBox_7)
        self.listView_9.setGeometry(QtCore.QRect(10, 40, 256, 21))
        self.listView_9.setObjectName("listView_9")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_15.setGeometry(QtCore.QRect(290, 40, 75, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 590, 371, 81))
        self.groupBox_8.setObjectName("groupBox_8")
        self.listView_10 = QtWidgets.QListView(self.groupBox_8)
        self.listView_10.setGeometry(QtCore.QRect(10, 40, 256, 21))
        self.listView_10.setObjectName("listView_10")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_16.setGeometry(QtCore.QRect(290, 40, 75, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_11.setGeometry(QtCore.QRect(600, 550, 121, 71))
        self.pushButton_11.setObjectName("pushButton_11")
        self.tabWidget.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1053, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "CCTV MASKING"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Load"))
        self.pushButton_4.setText(_translate("MainWindow", "Browse"))
        self.label_3.setText(_translate("MainWindow", "영상 들어갈 부분"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Tab 1"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Image Capture"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Load"))
        self.pushButton_14.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Training"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Save"))
        self.pushButton_6.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "영상 들어갈 부분"))
        self.label.setText(_translate("MainWindow", "동영상화면"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.groupBox.setTitle(_translate("MainWindow", "Load"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Play"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Load"))
        self.pushButton_15.setText(_translate("MainWindow", "Browse"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Save"))
        self.pushButton_16.setText(_translate("MainWindow", "Browse"))
        self.pushButton_11.setText(_translate("MainWindow", "Masking"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Masking"))

    def pushbutton4(self):
        filename = QFileDialog.etOpenFileName()
        self.pushbutton4.setText(filename[0])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
