# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'allui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtWidgets import QApplication, QWidget, QFileDialog
from PyQt5.QtCore import Qt, QUrl
from PyQt5.QtGui import QPalette
from PyQt5.uic import loadUi
from PyQt5.QtGui import QIcon, QFont
from PyQt5.QtCore import QDir, Qt, QUrl, QSize
from PyQt5.QtMultimedia import QMediaContent, QMediaPlayer, QMediaPlaylist
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtWidgets import (QApplication, QFileDialog, QHBoxLayout, QLabel,
        QPushButton, QSizePolicy, QSlider, QStyle, QVBoxLayout, QWidget, QStatusBar)
from PyQt5.QtMultimedia import QMediaPlaylist, QMediaPlayer, QMediaContent
from PyQt5.QtCore import QUrl, QObject, pyqtSignal
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtWidgets import QMessageBox
import sys
import datetime

from media1 import CMultiMedia


class Ui_Mozaic(QWidget):

    def setupUi(self, Mozaic):

        Mozaic.setObjectName("Mozaic")
        Mozaic.resize(1179, 786)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("cctv.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Mozaic.setWindowIcon(icon)

        # self.parent = Mozaic
        # self.player = QMediaPlayer(Mozaic, flags=QMediaPlayer.VideoSurface)
        # self.player.setVideoOutput(video_widget)
        # self.listWidget = QMediaPlaylist()
        # self.player.setPlaylist(self.listWidget)

        # self.mediaPlayer = QMediaPlayer(None, QMediaPlayer.VideoSurface)

        self.centralwidget = QtWidgets.QWidget(Mozaic)
        self.centralwidget.setObjectName("centralwidget")

        self.cctvlogo = QtWidgets.QLabel(self.centralwidget)
        self.cctvlogo.setGeometry(QtCore.QRect(390, 10, 171, 71))
        self.cctvlogo.setText("")
        self.cctvlogo.setObjectName("cctvlogo")
        self.qPixmapFileVar = QPixmap()
        self.qPixmapFileVar.load("cctv.png")
        self.qPixmapFileVar = self.qPixmapFileVar.scaledToWidth(200)

        self.cctvlogo.setPixmap(self.qPixmapFileVar)


        self.cctvwiget = QtWidgets.QTabWidget(self.centralwidget)
        self.cctvwiget.setGeometry(QtCore.QRect(10, 90, 1161, 631))
        self.cctvwiget.setObjectName("cctvwiget")

        self.Startinitializing = QtWidgets.QWidget()
        self.Startinitializing.setObjectName("Startinitializing")

        self.VideoLoadBox = QtWidgets.QGroupBox(self.Startinitializing)
        self.VideoLoadBox.setGeometry(QtCore.QRect(640, 310, 461, 101))
        self.VideoLoadBox.setObjectName("VideoLoadBox")

        # self.view = QVideoWidget()
        # #self.view.setAutoFillBackground(True)
        # self.view.setObjectName("view")
        # self.mediaPlayer.setVideoOutput(self.view)


        self.VideoLoadpath = QtWidgets.QLabel(self.VideoLoadBox)
        self.VideoLoadpath.setGeometry(QtCore.QRect(20, 50, 300, 20))
        self.VideoLoadpath.setObjectName("VideoLoadpath")

        self.LoadingButton = QtWidgets.QPushButton(self.VideoLoadBox)
        self.LoadingButton.setGeometry(QtCore.QRect(340, 40, 112, 34))
        self.LoadingButton.setObjectName("LoadingButton")

        self.SaveGroupBox = QtWidgets.QGroupBox(self.Startinitializing)
        self.SaveGroupBox.setGeometry(QtCore.QRect(640, 480, 461, 101))
        self.SaveGroupBox.setObjectName("SaveGroupBox")

        self.VideoSavePath = QtWidgets.QLabel(self.SaveGroupBox)
        self.VideoSavePath.setGeometry(QtCore.QRect(20, 50, 300, 20))
        self.VideoSavePath.setObjectName("VideoSavePath")

        self.SaveButton = QtWidgets.QPushButton(self.SaveGroupBox)
        self.SaveButton.setGeometry(QtCore.QRect(340, 40, 112, 34))
        self.SaveButton.setObjectName("SaveButton")

        self.InsertNameBox = QtWidgets.QGroupBox(self.Startinitializing)
        self.InsertNameBox.setGeometry(QtCore.QRect(640, 130, 461, 101))
        self.InsertNameBox.setObjectName("InsertNameBox")

        self.NameButton = QtWidgets.QPushButton(self.InsertNameBox)
        self.NameButton.setGeometry(QtCore.QRect(340, 40, 112, 34))
        self.NameButton.setObjectName("NameButton")

        self.Naming = QtWidgets.QLineEdit(self.InsertNameBox)
        self.Naming.setGeometry(QtCore.QRect(30, 40, 281, 34))
        self.Naming.setObjectName("Naming")

        self.SeeResultInitializing = QtWidgets.QTextBrowser(self.Startinitializing)
        self.SeeResultInitializing.setGeometry(QtCore.QRect(33, 20, 571, 561))
        self.SeeResultInitializing.setObjectName("SeeResultInitializing")

        self.cctvwiget.addTab(self.Startinitializing, "")

        self.Training = QtWidgets.QWidget()
        self.Training.setObjectName("Training")

        self.seeResultTraining = QtWidgets.QTextBrowser(self.Training)
        self.seeResultTraining.setGeometry(QtCore.QRect(50, 20, 821, 461))
        self.seeResultTraining.setObjectName("seeResultTraining")

        self.TrainingButton = QtWidgets.QPushButton(self.Training)
        self.TrainingButton.setGeometry(QtCore.QRect(50, 502, 241, 81))
        self.TrainingButton.setObjectName("TrainingButton")

        self.cctvwiget.addTab(self.Training, "")

        self.ConfirmVideo = QtWidgets.QWidget()
        self.ConfirmVideo.setObjectName("ConfirmVideo")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.ConfirmVideo)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 519, 741, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")

        self.MenuBar = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.MenuBar.setContentsMargins(10, 0, 10, 0)
        self.MenuBar.setSpacing(100)
        self.MenuBar.setObjectName("MenuBar")

        self.PlayButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PlayButton.setText("")
        self.PlayButton.setObjectName("PlayButton")

        self.MenuBar.addWidget(self.PlayButton)

        self.StopMomentButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.StopMomentButton.setText("")
        self.StopMomentButton.setObjectName("StopMomentButton")

        self.MenuBar.addWidget(self.StopMomentButton)

        self.PauseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PauseButton.setText("")
        self.PauseButton.setObjectName("PauseButton")

        self.MenuBar.addWidget(self.PauseButton)


        self.verticalLayoutWidget = QtWidgets.QWidget(self.ConfirmVideo)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 20, 811, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")

        self.horizontalSlider = QtWidgets.QSlider(self.widget)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 430, 751, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")

        self.verticalLayout_2.addWidget(self.widget)

        self.listWidget = QtWidgets.QListWidget(self.ConfirmVideo)
        self.listWidget.setGeometry(QtCore.QRect(865, 50, 287, 451))
        self.listWidget.setObjectName("listWidget")

        self.pushButton = QtWidgets.QPushButton(self.ConfirmVideo)
        self.pushButton.setGeometry(QtCore.QRect(890, 530, 112, 34))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self.ConfirmVideo)
        self.pushButton_2.setGeometry(QtCore.QRect(1020, 530, 112, 34))
        self.pushButton_2.setObjectName("pushButton_2")

        self.label = QtWidgets.QLabel(self.ConfirmVideo)
        self.label.setGeometry(QtCore.QRect(950, 20, 151, 18))
        self.label.setObjectName("label")

        self.cctvwiget.addTab(self.ConfirmVideo, "")

        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(800, 20, 321, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(30)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.HelpButton1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.HelpButton1.setText("")
        self.HelpButton1.setObjectName("HelpButton1")

        self.horizontalLayout_3.addWidget(self.HelpButton1)

        self.HelpButton2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.HelpButton2.setText("")
        self.HelpButton2.setObjectName("HelpButton2")

        self.horizontalLayout_3.addWidget(self.HelpButton2)

        self.HelpButton3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.HelpButton3.setText("")
        self.HelpButton3.setObjectName("HelpButton3")

        self.horizontalLayout_3.addWidget(self.HelpButton3)

        Mozaic.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(Mozaic)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1179, 31))
        self.menubar.setObjectName("menubar")

        Mozaic.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(Mozaic)
        self.statusbar.setObjectName("statusbar")

        Mozaic.setStatusBar(self.statusbar)



        # pal = QPalette()
        # pal.setColor(QPalette.Background,Qt.black)
        # self.view.setAutoFillBackground(True)
        # self.view.setPalette(pal)

        self.PlayButton.clicked.connect(self.PlayButtonM)
        # self.StopMomentButton.clicked.connect(self.StopMomentButtonM)
        # self.PauseButton.clicked.connect(self.PauseButtonM)
        # self.pushButton.clicked.connect(self.pushButtonM)
        # self.pushButton_2.clicked.connect(self.pushButton_2M)
        self.HelpButton1.clicked.connect(self.HelpButton1M)
        self.HelpButton2.clicked.connect(self.HelpButton2M)
        self.HelpButton3.clicked.connect(self.HelpButton3M)
        # self.horizontalSlider.sliderMoved.connect(self.barChanged)
        #self.listWidget.itemDoubleClicked.connect(self.dbClickList)
        self.LoadingButton.clicked.connect(self.LoadingButtonM)
        self.pushButton.clicked.connect(self.AddbuttonM)
        self.pushButton_2.clicked.connect(self.clickDel)

        # vboxLayout = QVBoxLayout()
        # vboxLayout.addWidget(self.view)
        #
        # self.setLayout(vboxLayout)



        self.HelpButton1.setStyleSheet('image:url(HELP1.png)')
        self.HelpButton2.setStyleSheet('image:url(HELP2.png)')
        self.HelpButton3.setStyleSheet('image:url(HELP3.png)')
        self.PlayButton.setStyleSheet('image:url(재생.png)')
        self.StopMomentButton.setStyleSheet('image:url(일시정지.png)')
        self.PauseButton.setStyleSheet('image:url(중지.png)')


        self.retranslateUi(Mozaic)
        self.cctvwiget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Mozaic)

    def retranslateUi(self, Mozaic):
        _translate = QtCore.QCoreApplication.translate
        Mozaic.setWindowTitle(_translate("Mozaic", "Mozaic"))
        self.VideoLoadBox.setTitle(_translate("Mozaic", "Load"))
        self.VideoLoadpath.setText(_translate("Mozaic", "LoadFile"))
        self.LoadingButton.setText(_translate("Mozaic", "Loading"))
        self.SaveGroupBox.setTitle(_translate("Mozaic", "Save"))
        self.VideoSavePath.setText(_translate("Mozaic", "SaveFile"))
        self.SaveButton.setText(_translate("Mozaic", "Saving"))
        self.InsertNameBox.setTitle(_translate("Mozaic", "Insert Name"))
        self.NameButton.setText(_translate("Mozaic", "Name"))
        self.cctvwiget.setTabText(self.cctvwiget.indexOf(self.Startinitializing), _translate("Mozaic", "Starting Initializing"))
        self.TrainingButton.setText(_translate("Mozaic", "Training"))
        self.cctvwiget.setTabText(self.cctvwiget.indexOf(self.Training), _translate("Mozaic", "Training"))
        self.pushButton.setText(_translate("Mozaic", "ADD"))
        self.pushButton_2.setText(_translate("Mozaic", "DELETE"))
        self.label.setText(_translate("Mozaic", "추가된 동영상"))
        self.cctvwiget.setTabText(self.cctvwiget.indexOf(self.ConfirmVideo), _translate("Mozaic", "Confirm Video"))


    def LoadingButtonM(self):
        fileName, _ = QFileDialog.getOpenFileName(self, "모자이크 동영상 선택",
                ".", "Video Files (*.mp4 *.flv *.ts *.mts *.avi)")
        if fileName != '':
            self.mediaPlayer.setMedia(
                    QMediaContent(QUrl.fromLocalFile(fileName)))
            self.QtMultimedia.QMediaPlayer.play()

    def PlayButtonM(self):
        print('a')
        self.mediaPlayer.play()
        print('aa')




    def AddbuttonM(self):
        files, ext = QFileDialog.getOpenFileName(self, "모자이크 동영상 선택",
                ".", "Video Files (*.mp4 *.flv *.ts *.mts *.avi)") #동영상 불러오기
        if files:
            #cnt = len(files)
            row = self.listWidget.count()

            #for i in range(row, row + cnt): # i=cnt
            self.listWidget.addItem(files)
            self.listWidget.setCurrentRow(row)

            #self.listWidget.addItem(files[0])
            #self.listWidget.setCurrentRow(0)

    #            self.mediaPlayer.addMedia(files)

    def clickDel(self):
        row = self.listWidget.currentRow()
        self.listWidget.takeItem(row)

    def HelpButton1M(self):
        QMessageBox.information(self,"Starting Initializing 도움말","본 Starting Initializing 서비스는 고객의 얼굴을 인식하여, "
                                             "미디어 상의 고객의 얼굴을 찾고자 Dataset을 마련하는 과정입니다.\n"
                                             "\n"
                                             "앞서 2, 3단계를 시작하기 전에 본 기기의 카메라에 얼굴을 댄 후, "
                                             "별도의 지시사항이 나오기 전에 대기하여 주십시오.\n"
                                                                 "\n")

    def HelpButton2M(self):
        QMessageBox.information(self, "Training 도움말", "본 Training 서비스는 1단계에서 인식한 고객의 얼굴을 바탕으로 생성된 "
                                               "Dataset을 이용하여, "
                                               "Mozaic 프로그램 상에 인식하는 과정입니다.\n"
                                               "\n"
                                               "앞서 3단계를 시작하기 전 별도의 지시사항이 나오기 전까지 대기하여 주십시오.\n"
                                                      "\n")

    def HelpButton3M(self):
        QMessageBox.information(self, "Confirm Video 도움말", "본 Confirm Video 서비스는 1,2단계에서 완료한 고객의 얼굴 인식을 바탕으로 영상처리하여"
                                               "실제 동영상을 확인하는 과정입니다.\n"
                                               "\n"
                                               "ADD버튼과 DELETE버튼을 이용하여 시청하고자 하는 영상을 리스트상에 추가 및 제거할 수 "
                                               "있으며, 영상의 배속을 조절할 수 있습니다.\n"
                                               "\n"
                                               "또한 영상을 재생, 중지, 일시 정지시킬수 도 있습니다.\n"
                                                           "\n")








if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mozaic = QtWidgets.QMainWindow()
    ui = Ui_Mozaic()
    ui.setupUi(Mozaic)
    Mozaic.show()
    sys.exit(app.exec_())
